#!/usr/bin/python3

import discord
from temp import produce_image

client = discord.Client()

@client.event
async def on_ready():
    print('Connected!')
    print('Username: ' + client.user.name)
    print('ID: ' + client.user.id)

name_list = ['nepeta', 'vriska', 'equius', 'karkat']

@client.event
async def on_message(message):
# we do not want the bot to reply to itself
    print(message.author)
    if str(message.channel) != "bot-channel":
        return
    name = str(message.content).split(' ')[0].lstrip('$')
    remainder = str(message.content).lstrip('$'+name)
    if message.author == client.user:
        return
    if message.content[0] != '$':
        return
    if name not in name_list:
        return
    await client.delete_message ( message )
    produce_image ( remainder, name )
    await client.send_file(message.channel, '/home/pi/Documents/out_img.png')

client.run(str(open('/home/pi/Documents/token_file').read()).rstrip('\n'))
