#!/usr/bin/python3

import discord
from temp import produce_image

client = discord.Client()

@client.event
async def on_ready():
    print('Connected!')
    print('Username: ' + client.user.name)
    print('ID: ' + client.user.id)

allowed_chars = ['$', '^', ')']

@client.event
async def on_message(message):
# we do not want the bot to reply to itself
    print(message.author)
    if str(message.channel) != "bot-channel":
        return
    if message.author == client.user:
        return
    if message.content[0] not in allowed_chars:
        return
    if message.content[0] == '$':
        name = 'nepeta'
    if message.content[0] == '^':
        name = 'vriska'
    if message.content[0] == ')':
        name = 'karkat'
    await client.delete_message ( message )
    produce_image ( message.content, name )
    await client.send_file(message.channel, '/home/pi/Documents/out_img.png')

client.run(str(open('/home/pi/Documents/token_file').read()).rstrip('\n'))
